language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - COVERAGE=false
  matrix:
    - MOODLE_BRANCH=MOODLE_27_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_27_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_28_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql
    - MOODLE_BRANCH=MOODLE_29_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_29_STABLE DB=pgsql
    
matrix:
  include:
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=mysqli
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=mysqli
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=master DB=mysqli
    - php: 7.0
      addons: 
        postgresql: 9.3
      env: MOODLE_BRANCH=master DB=pgsql
    
before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - git clone https://github.com/jfederico/moodle-plugin-ci.git ci
  - cd ci
  - composer config repositories.moodle-coding-standard vcs https://github.com/jfederico/moodle-coding-standard
  - composer config repositories.moodle-plugin-ci vcs https://github.com/jfederico/moodle-plugin-ci
  - composer require --prefer-dist moodlerooms/moodle-coding-standard:dev-master#6a4a63a1f265466417500050ff668a1b927b54ab
  - composer require --prefer-dist moodlerooms/moodle-plugin-ci:dev-master#45e7c2babaebd8068e67ade31116f70a2ab8b596
  - cd ..
  #- composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  #- moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  #- moodle-plugin-ci shifter
  #- moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
