language: php

sudo: false

addons:
  firefox: "47.0.1"
  postgresql: "9.3"
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  #- 5.4
  #- 5.5
  #- 5.6

env:
  global:
    - COVERAGE=false
  matrix:
    #- MOODLE_BRANCH=MOODLE_27_STABLE DB=mysqli
    #- MOODLE_BRANCH=MOODLE_27_STABLE DB=pgsql
    #- MOODLE_BRANCH=MOODLE_28_STABLE DB=mysqli
    #- MOODLE_BRANCH=MOODLE_28_STABLE DB=pgsql
    #- MOODLE_BRANCH=MOODLE_29_STABLE DB=mysqli
    #- MOODLE_BRANCH=MOODLE_29_STABLE DB=pgsql

matrix:
  include:
    #- php: 7.0
    #  env: MOODLE_BRANCH=MOODLE_30_STABLE DB=mysqli
    #- php: 7.0
    #  env: MOODLE_BRANCH=MOODLE_30_STABLE DB=pgsql
    #- php: 7.0
    #  env: MOODLE_BRANCH=MOODLE_31_STABLE DB=mysqli
    #- php: 7.0
    #  env: MOODLE_BRANCH=MOODLE_31_STABLE DB=pgsql
    #- php: 7.0
    #  env: MOODLE_BRANCH=MOODLE_32_STABLE DB=mysqli
    #- php: 7.0
    #  env: MOODLE_BRANCH=MOODLE_32_STABLE DB=pgsql
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_33_STABLE DB=mysqli
    #- php: 7.0
    #  env: MOODLE_BRANCH=MOODLE_33_STABLE DB=pgsql
    #- php: 7.0
    #  env: MOODLE_BRANCH=master DB=mysqli
    #  addons:
    #    postgresql: 9.3
    #- php: 7.0
    #  env: MOODLE_BRANCH=master DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install node
  - cd ../..
  ## Custom script
  #- composer selfupdate
  #- cd ../..
  #- git clone https://github.com/jfederico/moodle-plugin-ci.git ci
  #- cd ci
  #- composer config repositories.moodle-coding-standard '{"type":"vcs", "url":"https://github.com/jfederico/moodle-coding-standard", "no-api":true}'
  #- composer config repositories.moodle-plugin-ci '{"type":"vcs", "url":"https://github.com/jfederico/moodle-plugin-ci", "no-api":true}'
  #- composer require --prefer-dist moodlerooms/moodle-coding-standard:dev-master#6a4a63a1f265466417500050ff668a1b927b54ab
  #- composer require --prefer-dist moodlerooms/moodle-plugin-ci:dev-master#45e7c2babaebd8068e67ade31116f70a2ab8b596
  #- cd ..
  ## Standard script
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  ## Complete settings
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  #- moodle-plugin-ci phpcpd      ## Failing
  - moodle-plugin-ci phpmd
  #- moodle-plugin-ci codechecker
  #- moodle-plugin-ci validate    ## Failing
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
